server:
  port: 9095

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: admin
      password: admin
      database: compras

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

integration:
  apiclientes:
    url: http://localhost:9094
  apiprodutos:
    url: http://localhost:9091

