version: "3.2"

services:
  postgres-db:
    image: postgres
    container_name: postgres-compose
    environment:
      POSTGRES_PASSWORD: "docker"
    ports:
      - 5432:5432
  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbitmq-compose
    ports:
      - 5672:5672
      - 15672:15672
  mongodb:
    image: mongo:latest # use the latest image.
    container_name: mongodb
    restart: always
    environment: # set required env variables to access mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes: # optional to preserve database after container is deleted.
      - ./database-data:/data/db
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
