spring:
  mvc.pathmatch:
      matching-strategy: ant-path-matcher

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:file:C:\workspace\db
    password: ''

  h2:
    console:
      enabled: 'true'
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true